/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import config.Session;
import config.dbConnector;
import java.awt.Color;
import static java.awt.Color.pink;
import static java.awt.Color.red;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
import petcare.loginForm;



/**
 *
 * @author Yisha
 */
public class AddOwnerAdmin extends javax.swing.JFrame {

    /**
     * Creates new form adminDashboard
     */
    public AddOwnerAdmin() {
        initComponents();
        displayData();
    }
    boolean checkadd = true;
    



    Color navcolor = new Color(0,0,0);
    Color hovercolor = new Color(51,51,51);
    
    public void displayData(){
        try{
            dbConnector dbc = new dbConnector();
            try (ResultSet rs = dbc.getData("SELECT owner_id, owner_fname, owner_lname, owner_contact FROM tbl_owner")) {
                oTable.setModel(DbUtils.resultSetToTableModel(rs));
            }
        }catch(SQLException ex){
            System.out.println("Errors: "+ex.getMessage());

        }

    }
    
    public boolean duplicateOwnerCheck() {
    dbConnector dbc = new dbConnector();
    boolean isDuplicate = false;

    String query = "SELECT * FROM tbl_owner WHERE owner_fname = '" + ofname.getText() +
                   "' AND owner_lname = '" + olname.getText() +
                   "' AND owner_contact = '" + ocontact.getText() + "'";

    try {
        ResultSet rs = dbc.getData(query);
        if (rs.next()) {
            isDuplicate = true;
        }
    } catch (SQLException ex) {
        System.out.println("Duplicate check error: " + ex.getMessage());
    }

    return isDuplicate;
}
    
    public void clearFields() {
    oid.setText("");    
    ofname.setText("");
    olname.setText("");
    ocontact.setText("");
    oaddress.setText("");
}

private void loadOwners() {
    DefaultTableModel model = (DefaultTableModel) oTable.getModel();
    model.setRowCount(0);  // limpyohi ang table una

    dbConnector dbc = new dbConnector();
    String query = "SELECT * FROM tbl_owner";

    try {
        ResultSet rs = dbc.getData(query);
        while (rs.next()) {
            Object[] row = {
                rs.getInt("owner_id"),
                rs.getString("owner_fname"),
                rs.getString("owner_lname"),
                rs.getString("owner_contact"),
                rs.getString("owner_address")
            };
            model.addRow(row);
        }
    } catch (SQLException e) {
    }
}




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        oTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        acc_id = new javax.swing.JLabel();
        acc_name = new javax.swing.JLabel();
        p_add = new javax.swing.JPanel();
        add = new javax.swing.JPanel();
        addlabel = new javax.swing.JLabel();
        clear = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        update = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lname = new javax.swing.JLabel();
        oaddress = new javax.swing.JTextField();
        ocontact = new javax.swing.JTextField();
        olname = new javax.swing.JTextField();
        ofname = new javax.swing.JTextField();
        oid = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        oTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        oTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(oTable);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 430, 520));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setText("OWNER RECORDS");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Back_Clipart_Vector__Vector_Back_Icon__Back_Icons__Arrow__Back_PNG_Image_For_Free_Download-removebg-preview (1).png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 60, 60));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        acc_id.setBackground(new java.awt.Color(255, 204, 204));
        acc_id.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        acc_id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acc_id.setText("ID");
        jPanel1.add(acc_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 180, 30));

        acc_name.setBackground(new java.awt.Color(255, 204, 204));
        acc_name.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        acc_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acc_name.setText("User");
        jPanel1.add(acc_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 180, 30));

        p_add.setBackground(new java.awt.Color(51, 51, 51));
        p_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p_addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p_addMouseExited(evt);
            }
        });
        p_add.setLayout(null);

        add.setBackground(new java.awt.Color(153, 153, 255));
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMouseExited(evt);
            }
        });
        add.setLayout(null);

        addlabel.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        addlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addlabel.setText("ADD");
        add.add(addlabel);
        addlabel.setBounds(20, 10, 140, 30);

        p_add.add(add);
        add.setBounds(0, 0, 180, 50);

        jPanel1.add(p_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 180, 50));

        clear.setBackground(new java.awt.Color(153, 153, 255));
        clear.setForeground(new java.awt.Color(204, 204, 204));
        clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearMouseExited(evt);
            }
        });
        clear.setLayout(null);

        jLabel17.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("CLEAR");
        clear.add(jLabel17);
        jLabel17.setBounds(20, 10, 140, 30);

        jPanel1.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 180, 50));

        update.setBackground(new java.awt.Color(153, 153, 255));
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateMouseExited(evt);
            }
        });
        update.setLayout(null);

        jLabel19.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("UPDATE");
        update.add(jLabel19);
        jLabel19.setBounds(20, 10, 140, 30);

        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 180, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userimages/Screenshot 2026-03-03 165200.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 130, 130));
        jPanel1.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 190, 30));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 680));

        oaddress.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        oaddress.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Address:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 0, 18))); // NOI18N
        oaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oaddressActionPerformed(evt);
            }
        });
        jPanel3.add(oaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 520, 330, 70));

        ocontact.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ocontact.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Contact:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 0, 18))); // NOI18N
        ocontact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ocontactActionPerformed(evt);
            }
        });
        jPanel3.add(ocontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 420, 330, 70));

        olname.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        olname.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Last Name:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 0, 18))); // NOI18N
        olname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                olnameActionPerformed(evt);
            }
        });
        jPanel3.add(olname, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 320, 330, 70));

        ofname.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ofname.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "First Name:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 0, 18))); // NOI18N
        ofname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ofnameActionPerformed(evt);
            }
        });
        jPanel3.add(ofname, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, 330, 70));

        oid.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        oid.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Owner ID:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 0, 18))); // NOI18N
        oid.setEnabled(false);
        oid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oidActionPerformed(evt);
            }
        });
        jPanel3.add(oid, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 120, 330, 70));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       Session sess = Session.getInstance();
       if(sess.getUid()==0){
           JOptionPane.showMessageDialog(null, "No account, Login First!");
           loginForm lf = new loginForm();
           lf.setVisible(true);
           this.dispose();           
       }else{
       acc_name.setText(""+sess.getFname());
       lname.setText(""+sess.getLname());
       acc_id.setText(""+sess.getUid());
           
       }  
           
    }//GEN-LAST:event_formWindowActivated

    private void oTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oTableMouseClicked
     
        ofname.setEnabled(false);
        olname.setEnabled(false);
        int rowIndex = oTable.getSelectedRow();
      if(rowIndex < 0){
          JOptionPane.showMessageDialog(null, "Please select an item!");         
      }else{
          try{
              dbConnector dbc = new dbConnector();
              TableModel tbl = oTable.getModel();
              ResultSet rs = dbc.getData("SELECT * FROM tbl_owner WHERE owner_id ='"+tbl.getValueAt(rowIndex, 0)+"'");
              if(rs.next()){
                  createUserForm crf = new createUserForm();
                  oid.setText(""+rs.getInt("owner_id"));
                  ofname.setText(""+rs.getString("owner_fname"));
                  olname.setText(""+rs.getString("owner_lname"));
                  ocontact.setText(""+rs.getString("owner_contact"));
                  oaddress.setText(""+rs.getString("owner_address"));

                  add.setEnabled(false);
                  addlabel.setForeground(red);
                  checkadd = false;

                  

              }
          }catch(SQLException ex){
              System.out.println(""+ex);
          }
          
      } 
    }//GEN-LAST:event_oTableMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        AppointmentsAdmin aa = new AppointmentsAdmin();
        aa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
   if(checkadd){
       
       
        ofname.setEnabled(true);
        olname.setEnabled(true);
        
    if(ofname.getText().isEmpty() || olname.getText().isEmpty() ||
       ocontact.getText().isEmpty() || oaddress.getText().isEmpty()) {

        JOptionPane.showMessageDialog(null, "All fields are required!");

    } else if (!ocontact.getText().matches("^[0-9]{10,11}$")) {
        JOptionPane.showMessageDialog(null, "Invalid contact number!");
        ocontact.setText("");

    } else if(duplicateOwnerCheck()) {
        JOptionPane.showMessageDialog(null, "Owner already exists!");

    } else {
        dbConnector dbc = new dbConnector();
String query = "INSERT INTO tbl_owner (owner_fname, owner_lname, owner_contact, owner_address) VALUES ('" +
                        ofname.getText() + "', '" + olname.getText() + "', '" +
                        ocontact.getText() + "', '" + oaddress.getText() + "')";


        if (dbc.insertData(query) > 0) {
            JOptionPane.showMessageDialog(null, "Owner added successfully!");
            clearFields();
            loadOwners();
        } else {
            JOptionPane.showMessageDialog(null, "Failed to add owner.");
        }
    }
   }




        
    }//GEN-LAST:event_addMouseClicked

    private void addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseEntered
       
    }//GEN-LAST:event_addMouseEntered

    private void addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseExited
        
    }//GEN-LAST:event_addMouseExited

    private void p_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_addMouseClicked
        createUserForm crf = new createUserForm();
        crf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_p_addMouseClicked

    private void p_addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_addMouseEntered

    }//GEN-LAST:event_p_addMouseEntered

    private void p_addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_addMouseExited

    }//GEN-LAST:event_p_addMouseExited

    private void clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseClicked

        ofname.setEnabled(true);
        olname.setEnabled(true);
        checkadd = true;
        addlabel.setForeground(pink);
        oid.setText("");
        ofname.setText("");
        olname.setText("");
        ocontact.setText("");
        oaddress.setText("");

    }//GEN-LAST:event_clearMouseClicked

    private void clearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseEntered
        
    }//GEN-LAST:event_clearMouseEntered

    private void clearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseExited
        
    }//GEN-LAST:event_clearMouseExited

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
   
        ofname.setEnabled(false);
        olname.setEnabled(false);
        
    if (oid.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please select an owner first!");
        return;
    }
        ofname.setEnabled(false);
        olname.setEnabled(false);
    
    if (ocontact.getText().isEmpty() || oaddress.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Contact and Address are required!");
    } else if (!ocontact.getText().matches("^[0-9]{11}$")) {
        JOptionPane.showMessageDialog(null, "Invalid contact number! Must be 11 digits.");
        ocontact.setText("");
    } else {
        dbConnector dbc = new dbConnector();
        dbc.updateData("UPDATE tbl_owner SET owner_contact = '" + ocontact.getText() + 
            "', owner_address = '" + oaddress.getText() + 
            "' WHERE owner_id = '" + oid.getText() + "'");


        setVisible(true);
        clearFields();
        
                ofname.setEnabled(true);
        olname.setEnabled(true);

    }

    }//GEN-LAST:event_updateMouseClicked

    private void updateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseEntered
        
    }//GEN-LAST:event_updateMouseEntered

    private void updateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseExited
        
    }//GEN-LAST:event_updateMouseExited

    private void oaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oaddressActionPerformed

    private void ocontactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ocontactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ocontactActionPerformed

    private void olnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_olnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_olnameActionPerformed

    private void ofnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ofnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ofnameActionPerformed

    private void oidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddOwnerAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddOwnerAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddOwnerAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddOwnerAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AddOwnerAdmin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acc_id;
    private javax.swing.JLabel acc_name;
    private javax.swing.JPanel add;
    private javax.swing.JLabel addlabel;
    private javax.swing.JPanel clear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lname;
    private javax.swing.JTable oTable;
    private javax.swing.JTextField oaddress;
    private javax.swing.JTextField ocontact;
    public javax.swing.JTextField ofname;
    private javax.swing.JTextField oid;
    public javax.swing.JTextField olname;
    private javax.swing.JPanel p_add;
    private javax.swing.JPanel update;
    // End of variables declaration//GEN-END:variables
}
