/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import User.*;
import config.Session;
import config.dbConnector;
import java.awt.Color;
import java.awt.Component;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;
import petcare.loginForm;



/**
 *
 * @author Yisha
 */
public final class AppointmentFormAdmin extends javax.swing.JFrame {

    /**
     * Creates new form adminDashboard
     */
    public AppointmentFormAdmin() {
        initComponents();
        displayOwnerPetData();

    }
    
    Color navcolor = new Color(0,0,0);
    Color hovercolor = new Color(51,51,51);
    
public void displayOwnerPetData() { 
    try {
        dbConnector dbc = new dbConnector();

        String query = "SELECT a.app_id, " +  // Appointment ID first
                       "o.owner_id, CONCAT(o.owner_fname, ' ', o.owner_lname) AS owner_name, " +
                       "p.pet_id, p.pet_name, " +
                       "a.service_type, a.appointment_date, a.appointment_time, a.status " +
                       "FROM tbl_owner o " +
                       "JOIN tbl_pet p ON o.owner_id = p.owner_id " +
                       "JOIN tbl_appointment a ON p.pet_id = a.pet_id";

        // Display the ResultSet into JTable using rs2xml
        try (ResultSet rs = dbc.getData(query)) {
            // Display the ResultSet into JTable using rs2xml
            appTable.setModel(DbUtils.resultSetToTableModel(rs));
        }
    } catch (SQLException ex) {
        System.out.println("Error loading owner-pet data: " + ex.getMessage());
    }
}

private void filterTable() {
    DefaultTableModel ob = (DefaultTableModel) appTable.getModel(); 
    TableRowSorter<DefaultTableModel> obj = new TableRowSorter<>(ob); 
    appTable.setRowSorter(obj); 

    List<RowFilter<Object, Object>> filters = new ArrayList<>();

    // Add filter for jTextField1 (column 5)
    String text1 = jTextField1.getText().trim();
    if (!text1.isEmpty()) {
        filters.add(RowFilter.regexFilter("(?i)" + text1, 5)); // (?i) for case-insensitive
    }

    // Add filter for jTextField2 (column 8)
    String text2 = jTextField2.getText().trim();
    if (!text2.isEmpty()) {
        filters.add(RowFilter.regexFilter("(?i)" + text2, 8));
    }

    RowFilter<DefaultTableModel, Object> combinedFilter = RowFilter.andFilter(filters);
    obj.setRowFilter(combinedFilter);
}





    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        appTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        acc_id = new javax.swing.JLabel();
        acc_name = new javax.swing.JLabel();
        u_add = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        print = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lname = new javax.swing.JLabel();
        stype = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();
        name1 = new javax.swing.JLabel();
        pname1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        appTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        appTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                appTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(appTable);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 790, 450));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setText("APPOINTMENTS");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 240, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Back_Clipart_Vector__Vector_Back_Icon__Back_Icons__Arrow__Back_PNG_Image_For_Free_Download-removebg-preview (1).png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 60, 60));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        acc_id.setBackground(new java.awt.Color(255, 204, 204));
        acc_id.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        acc_id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acc_id.setText("ID");
        jPanel1.add(acc_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 180, 30));

        acc_name.setBackground(new java.awt.Color(255, 204, 204));
        acc_name.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        acc_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acc_name.setText("User");
        jPanel1.add(acc_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 190, 30));

        u_add.setBackground(new java.awt.Color(255, 204, 204));
        u_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                u_addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                u_addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                u_addMouseExited(evt);
            }
        });
        u_add.setLayout(null);

        jLabel15.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("ADD");
        u_add.add(jLabel15);
        jLabel15.setBounds(20, 10, 170, 30);

        jPanel1.add(u_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        print.setBackground(new java.awt.Color(204, 204, 204));
        print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                printMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                printMouseExited(evt);
            }
        });
        print.setLayout(null);

        jLabel18.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("PRINT");
        print.add(jLabel18);
        jLabel18.setBounds(10, 10, 140, 30);

        jPanel1.add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, 160, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userimages/Screenshot 2026-03-03 165200.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 130, -1));
        jPanel1.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 190, 30));
        jPanel1.add(stype, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 190, 30));
        jPanel1.add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 190, 30));
        jPanel1.add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 190, 30));
        jPanel1.add(pname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 190, 30));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 680));

        jTextField1.setBackground(new java.awt.Color(204, 204, 255));
        jTextField1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Search for Service Type:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 0, 18))); // NOI18N
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 310, 60));

        jTextField2.setBackground(new java.awt.Color(204, 204, 255));
        jTextField2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Search for Status:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 1, 18))); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });
        jPanel3.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 130, 310, 60));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       Session sess = Session.getInstance();
       if(sess.getUid()==0){
           JOptionPane.showMessageDialog(null, "No account, Login First!");
           loginForm lf = new loginForm();
           lf.setVisible(true);
           this.dispose();           
       }else{
       acc_name.setText(""+sess.getFname());
       lname.setText(""+sess.getLname());
       acc_id.setText(""+sess.getUid());
           
       }  
          
    }//GEN-LAST:event_formWindowActivated

    private void appTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appTableMouseClicked
     

    }//GEN-LAST:event_appTableMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        AppointmentsAdmin aa = new AppointmentsAdmin();
        aa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void u_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_u_addMouseClicked
        createUserForm crf = new createUserForm();
        crf.setVisible(true);
        //      crf.update.setEnabled(false);
        crf.update.setEnabled(false);
        for (Component c : crf.update.getComponents()) {
            c.setEnabled(false);
        }
        crf.remove.setEnabled(false);
        crf.select.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_u_addMouseClicked

    private void u_addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_u_addMouseEntered
        u_add.setBackground(hovercolor);
    }//GEN-LAST:event_u_addMouseEntered

    private void u_addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_u_addMouseExited
        u_add.setBackground(navcolor);
    }//GEN-LAST:event_u_addMouseExited

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
filterTable();
     }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
filterTable();
    }//GEN-LAST:event_jTextField2KeyReleased

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void printMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printMouseClicked
  int rowIndex = appTable.getSelectedRow(); // select from appointment table

    if (rowIndex < 0) {
        JOptionPane.showMessageDialog(null, "Please select a record to print!");
        return;
    }

    try {
        dbConnector dbc = new dbConnector();

        TableModel tbl = appTable.getModel();
        String appointmentId = tbl.getValueAt(rowIndex, 0).toString();

        // First check the status of the appointment
        String statusQuery = "SELECT status FROM tbl_appointment WHERE app_id = '" + appointmentId + "'";
        ResultSet statusRs = dbc.getData(statusQuery);

        if (statusRs.next()) {
            String status = statusRs.getString("status");
            System.out.println("DEBUG: Appointment status='" + status + "'"); // debug print

            if (!status.trim().equalsIgnoreCase("Completed")) {
                JOptionPane.showMessageDialog(null, "Cannot print receipt because the status is not completed.");
                return; // Exit the method so no receipt is shown
            }
        } else {
            JOptionPane.showMessageDialog(null, "Appointment record not found.");
            return;
        }

        // If status is completed, proceed with fetching data and showing receipt
        String query = "SELECT a.appointment_date, a.service_type, a.remarks, a.medications, " +
                       "CONCAT(o.owner_fname, ' ', o.owner_lname) AS owner_name, p.pet_name " +
                       "FROM tbl_appointment a " +
                       "JOIN tbl_owner o ON a.owner_id = o.owner_id " +
                       "JOIN tbl_pet p ON a.pet_id = p.pet_id " +
                       "WHERE a.app_id = '" + appointmentId + "'";

        ResultSet rs = dbc.getData(query);

        if (rs.next()) {
            receipt ipt = new receipt();

            stype.setText(java.time.LocalDate.now().toString()); // shows today's date
            stype.setText(rs.getString("owner_name"));
            stype.setText(rs.getString("pet_name"));
            stype.setText(rs.getString("service_type"));
            ipt.rm.setText(rs.getString("remarks"));
            ipt.meds.setText(rs.getString("medications"));

            // Get logged-in vet name (assume session username is saved in `acc_id`)
            String vetQuery = "SELECT u_fname, u_lname FROM tbl_user WHERE u_username = '" + acc_id + "'";
            ResultSet vetRs = dbc.getData(vetQuery);
            if (vetRs.next()) {
                String fullVetName = vetRs.getString("u_fname") + " " + vetRs.getString("u_lname");
                ipt.uname.setText(fullVetName);
            }

            ipt.setVisible(true);
            this.dispose();
        }

    } catch (SQLException ex) {
        System.out.println("Error: " + ex);
    }
    }//GEN-LAST:event_printMouseClicked

    private void printMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printMouseEntered
        print.setBackground(hovercolor);
    }//GEN-LAST:event_printMouseEntered

    private void printMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printMouseExited
        print.setBackground(navcolor);
    }//GEN-LAST:event_printMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppointmentFormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppointmentFormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppointmentFormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppointmentFormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AppointmentFormAdmin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acc_id;
    private javax.swing.JLabel acc_name;
    private javax.swing.JTable appTable;
    private javax.swing.JLabel date1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lname;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel pname1;
    private javax.swing.JPanel print;
    private javax.swing.JLabel stype;
    private javax.swing.JPanel u_add;
    // End of variables declaration//GEN-END:variables
}
