/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User;

import Admin.*;
import config.PanelPrinter;
import config.Session;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import petcare.loginForm;

/**
 *
 * @author Yisha
 */
public class receipt extends javax.swing.JFrame {

    /**
     * Creates new form individualPrinting
     */
    public receipt() {
        initComponents();
    }
    
    Color navcolor = new Color(51,51,51);
    Color hovercolor = new Color(102,102,102);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        page = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        rm = new javax.swing.JTextField();
        oname = new javax.swing.JTextField();
        meds = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        oname1 = new javax.swing.JTextField();
        oname2 = new javax.swing.JTextField();
        uname = new javax.swing.JTextField();
        oname4 = new javax.swing.JTextField();
        print1 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        page.setBackground(new java.awt.Color(255, 255, 255));
        page.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel15.setText("PET CLINIC");
        page.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 230, -1));

        jLabel17.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Colon Integrated School City of Naga, Cebu");
        page.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 370, -1));

        jLabel18.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel18.setText("+639123456789");
        page.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 140, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/download__6_-removebg-preview (3).png"))); // NOI18N
        page.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 50, 40));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/download__7_-removebg-preview.png"))); // NOI18N
        page.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 470, 40));

        jLabel23.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/download__7_-removebg-preview.png"))); // NOI18N
        page.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 140, 460, 60));

        jLabel24.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel24.setText("Date:");
        page.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 80, 30));

        jLabel27.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel27.setText("Medication(s):");
        page.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 140, -1));

        jLabel32.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel32.setText("Owner Name:");
        page.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 120, 30));

        jLabel33.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel33.setText("Pet Name:");
        page.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 120, 30));

        jLabel28.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel28.setText("Veterinarian:");
        page.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 120, 30));

        jLabel30.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel30.setText("Service Type:");
        page.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 140, 30));

        jLabel34.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel34.setText("Remarks:");
        page.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 100, -1));

        rm.setBackground(new java.awt.Color(204, 204, 204));
        rm.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        rm.setText(" ");
        rm.setBorder(null);
        rm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmActionPerformed(evt);
            }
        });
        page.add(rm, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, 310, 90));

        oname.setBackground(new java.awt.Color(204, 204, 204));
        oname.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        oname.setBorder(null);
        oname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onameActionPerformed(evt);
            }
        });
        page.add(oname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 310, 30));

        meds.setBackground(new java.awt.Color(204, 204, 204));
        meds.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        meds.setBorder(null);
        meds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medsActionPerformed(evt);
            }
        });
        page.add(meds, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 600, 310, 130));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/download__7_-removebg-preview.png"))); // NOI18N
        page.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 470, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userimages/Screenshot 2026-03-03 182008.png"))); // NOI18N
        page.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        oname1.setBackground(new java.awt.Color(204, 204, 204));
        oname1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        oname1.setBorder(null);
        oname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oname1ActionPerformed(evt);
            }
        });
        page.add(oname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 310, 30));

        oname2.setBackground(new java.awt.Color(204, 204, 204));
        oname2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        oname2.setBorder(null);
        oname2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oname2ActionPerformed(evt);
            }
        });
        page.add(oname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 310, 30));

        uname.setBackground(new java.awt.Color(204, 204, 204));
        uname.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        uname.setBorder(null);
        uname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unameActionPerformed(evt);
            }
        });
        page.add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 310, 30));

        oname4.setBackground(new java.awt.Color(204, 204, 204));
        oname4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        oname4.setBorder(null);
        oname4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oname4ActionPerformed(evt);
            }
        });
        page.add(oname4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 310, 30));

        jPanel1.add(page, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 890, 790));

        print1.setBackground(new java.awt.Color(204, 204, 204));
        print1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                print1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                print1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                print1MouseExited(evt);
            }
        });
        print1.setLayout(null);

        jLabel19.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("PRINT");
        print1.add(jLabel19);
        jLabel19.setBounds(0, 10, 140, 30);

        jPanel1.add(print1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 920, 140, 50));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/arrow1.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 90, 60));

        jTextField1.setBackground(new java.awt.Color(153, 153, 255));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jTextField1.setText("PRINTING FORM");
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 1010));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        AppointmentsAdmin appa = new AppointmentsAdmin();
        appa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void rmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rmActionPerformed

    private void onameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_onameActionPerformed

    private void medsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medsActionPerformed

    private void print1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_print1MouseClicked
     
JPanel myPanel =  new JPanel();
PanelPrinter pPrint =  new PanelPrinter(page);
pPrint.printPanel();
    }//GEN-LAST:event_print1MouseClicked

    private void print1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_print1MouseEntered
        
    }//GEN-LAST:event_print1MouseEntered

    private void print1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_print1MouseExited
        
    }//GEN-LAST:event_print1MouseExited

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
Session sess = Session.getInstance();
if(sess.getUid() == 0){
    JOptionPane.showMessageDialog(null, "No account, Login First!");
    loginForm lf = new loginForm();
    lf.setVisible(true);
    this.dispose();           
} else {
     uname.setText(sess.getFname() + " " + sess.getLname()); // Combine first and last name
}

      }//GEN-LAST:event_formWindowActivated

    private void oname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oname1ActionPerformed

    private void oname2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oname2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oname2ActionPerformed

    private void unameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unameActionPerformed

    private void oname4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oname4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oname4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new receipt().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JTextField meds;
    public javax.swing.JTextField oname;
    public javax.swing.JTextField oname1;
    public javax.swing.JTextField oname2;
    public javax.swing.JTextField oname4;
    private javax.swing.JPanel page;
    private javax.swing.JPanel print1;
    public javax.swing.JTextField rm;
    public javax.swing.JTextField uname;
    // End of variables declaration//GEN-END:variables

    public class stype {

        public stype() {
        }
    }
}
